services:
  practiq-be:
    build: .
    ports:
      - "8083:8083"
    env_file: .env
    environment:
      - DB_HOST=practiq-postgres-db
      - DATABASE_URL=postgres://postgres:postgres@practiq-postgres-db:5432/practiq-db?sslmode=disable
    depends_on:
      practiq-postgres-db:
        condition: service_healthy
    networks:
      - practiq-network

  practiq-postgres-db:
    image: postgres:14-alpine
    ports:
      - "54323:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: practiq-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - practiq-network

networks:
  practiq-network:
    driver: bridge
