ALTER TABLE notebook_pages
ADD COLUMN IF NOT EXISTS statement_text TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS statement_verified BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE notebook_submissions
ADD COLUMN IF NOT EXISTS needs_teacher_review BOOLEAN NOT NULL DEFAULT FALSE;
